//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontoffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportEntries
    {
        public ReportEntries()
        {
            this.UserSettings = new HashSet<UserSettings>();
        }
    
        public string EntryId { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public string EntryUser { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<UserSettings> UserSettings { get; set; }
    }
}
